# Generated by Django 3.0.4 on 2020-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodBankManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbankbeneficiary',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
