# Generated by Django 3.0.4 on 2020-04-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodBankManage', '0002_auto_20200411_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grampanchayat',
            name='members',
        ),
        migrations.AddField(
            model_name='grampanchayat',
            name='blockna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodBankManage.Block'),
        ),
    ]
