# Generated by Django 3.0.4 on 2020-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodBankManage', '0004_auto_20200412_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBankInventrycook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('gram', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now=True)),
                ('Available', models.PositiveIntegerField()),
                ('Recieved_Bhamashah', models.PositiveIntegerField()),
                ('Recieved_Government', models.PositiveIntegerField()),
                ('Recieved_NGO', models.PositiveIntegerField()),
                ('Distributed', models.PositiveIntegerField()),
                ('Required', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodBankInventryDry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('gram', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now=True)),
                ('Available', models.PositiveIntegerField()),
                ('Recieved_Bhamashah', models.PositiveIntegerField()),
                ('Recieved_Government', models.PositiveIntegerField()),
                ('Recieved_NGO', models.PositiveIntegerField()),
                ('Distributed', models.PositiveIntegerField()),
                ('Required', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodBankInventrymid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50)),
                ('gram', models.CharField(max_length=50)),
                ('date_added', models.DateField(auto_now=True)),
                ('Available_Wheat_Kgs', models.PositiveIntegerField()),
                ('Recieved_Wheat_Kgs', models.PositiveIntegerField()),
                ('Distributed_Wheat_Kgs', models.PositiveIntegerField()),
                ('Required_Wheat_Kgs', models.PositiveIntegerField()),
                ('Available_Rice_Kgs', models.PositiveIntegerField()),
                ('Recieved_Rice_Kgs', models.PositiveIntegerField()),
                ('Distributed_Rice_Kgs', models.PositiveIntegerField()),
                ('Required_Rice_Kgs', models.PositiveIntegerField()),
            ],
        ),
    ]
